UPDATE UNS2_MIGRATION_TEST.CHANNEL_METADATA_ELEMENTS CM
SET CM.FILTERED=TRUE
where METADATA_ELEMENT_ID in
(select me.ID from UNS2_MIGRATION_TEST.METADATA_ELEMENTS me where me.NAME in
(select choo.PROPERTY from UNS1_PRODUCTION.choosable choo where choo.CHANNEL_ID=CM.CHANNEL_ID)
)
