package com.eurodyn.uns.model;

// Generated Apr 16, 2006 9:40:13 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;

/**
 * Delivery generated by hbm2java
 */

public class Delivery implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 6443270929313798783L;

	private int   deliveryStatus;

	private Date deliveryTime;
	
	private DeliveryType deliveryType;

	// Constructors

	/** default constructor */
	public Delivery() {
	}

	// Property accessors

	public int getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(int deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	public DeliveryType getDeliveryType() {
		return deliveryType;
	}
	
	public void setDeliveryType(DeliveryType deliveryType) {
		this.deliveryType = deliveryType;
	}
}
