/*
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 * 
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 * 
 * The Original Code is Unified Notification System
 * 
 * The Initial Owner of the Original Code is European Environment
 * Agency (EEA).  Portions created by European Dynamics (ED) company are
 * Copyright (C) by European Environment Agency.  All Rights Reserved.
 * 
 * Contributors(s):
 *    Original code: Sasha Milosavljevic (ED) 
 */

package com.eurodyn.uns.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by hbm2java
 */

public class Notification implements java.io.Serializable {

	private static final long serialVersionUID = -627978637993389871L;
	// Fields	
	private int id;

	private int userId;

	private long eventId;

	private String content;

	private int channelId;

	private String subject;

	private Set deliveries = new HashSet(0);

	private User user;
	
	// Constructors

	/** default constructor */
	public Notification() {
	}

	/** minimal constructor */
	public Notification(int id, int userId, long eventId, String content, int channelId) {
		this.id = id;
		this.userId = userId;
		this.eventId = eventId;
		this.content = content;
		this.channelId = channelId;
	}

	/** full constructor */
	public Notification(int id, int userId, long eventId, String content, int channelId, String subject, Set deliveries) {
		this.id = id;
		this.userId = userId;
		this.eventId = eventId;
		this.content = content;
		this.channelId = channelId;
		this.subject = subject;
		this.deliveries = deliveries;
	}

	// Property accessors

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getuserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public long getEventId() {
		return this.eventId;
	}

	public void seteventId(long eventId) {
		this.eventId = eventId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getChannelId() {
		return this.channelId;
	}

	public void setChannelId(int channelId) {
		this.channelId = channelId;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Set getDeliveries() {
		return this.deliveries;
	}

	public void setDeliveries(Set deliveries) {
		this.deliveries = deliveries;
	}

	public User getUser() {
		return user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}
}
